import type {
  Asset,
  DocumentItem,
  FamilyMember,
  FamilyProfile,
  OwnershipGraph,
  TransferStep,
} from "./types";

export const FAMILY: FamilyMember[] = [
  { id: "father", name: "คุณพ่อ", shortName: "พ่อ", relation: "parent" },
  { id: "mother", name: "คุณแม่", shortName: "แม่", relation: "parent" },
  { id: "eldest", name: "บุตรคนโต", shortName: "คนโต", relation: "child" },
  {
    id: "youngest",
    name: "บุตรคนเล็ก",
    shortName: "คนเล็ก",
    relation: "child",
  },
  {
    id: "child_3",
    name: "บุตรคนที่ 3",
    shortName: "คนที่ 3",
    relation: "child",
  },
];

export const INITIAL_FAMILY_PROFILE: FamilyProfile = {
  name: "ตระกูล Wealth",
  note: "ใช้สำหรับวางแผนโอนทรัพย์สินและประมาณการภาษี",
};
export const INITIAL_ASSETS: Asset[] = [
  {
    id: "a1",
    type: "finance",
    name: "บัญชีออมทรัพย์ XYZ",
    value: 6_200_000,
    valuationDate: "2569-01",
    ownership: [{ personId: "father", percent: 100 }],
    beneficiaries: ["father"],
    plan: "keep",
    documents: "complete",
    ownerEntityKind: "individual",
  },
  {
    id: "a2",
    type: "real_estate",
    name: "ที่ดินบางละมุง",
    value: 38_000_000,
    valuationDate: "2565-06",
    ownership: [
      { personId: "father", percent: 50 },
      { personId: "mother", percent: 50 },
    ],
    beneficiaries: ["eldest", "youngest", "child_3"],
    plan: "transfer",
    documents: "outdated",
    ownerEntityKind: "individual",
    heirCount: 3,
    recipientRelation: "lineal_descendant",
    realEstate: {
      subtype: "land",
      area: { rai: 2, ngan: 1, sqWah: 50 },
      // 2*400 + 1*100 + 50 = 950 ตร.ว. × 40,000 ≈ 38M
      appraisalPerSqWah: 40_000,
      salePrice: 40_000_000,
      acquiredYearBe: 2555,
      transferYearBe: 2571,
      acquisitionMethod: "purchase_or_other",
    },
  },
  {
    id: "a3",
    type: "business",
    name: "หุ้นบริษัท ABC จำกัด",
    value: 210_000_000,
    valuationDate: "2569-03",
    ownership: [
      { personId: "father", percent: 60, role: "ประธาน" },
      { personId: "eldest", percent: 40 },
    ],
    beneficiaries: [],
    plan: "undecided",
    documents: "incomplete",
    controlPersonId: "father",
    ownerEntityKind: "individual",
    heirCount: 1,
    recipientRelation: "lineal_descendant",
    share: {
      subtype: "unlisted",
      companyName: "บริษัท ABC จำกัด",
      registeredCapital: 100_000_000,
      ownershipPercent: 60,
      parValue: 100_000_000,
      bookValue: 210_000_000,
      marketValue: 210_000_000,
      costBasis: 60_000_000,
    },
  },
  {
    id: "a4",
    type: "other",
    name: "กรมธรรม์ประกันชีวิต",
    value: 5_000_000,
    valuationDate: "2568-12",
    ownership: [{ personId: "father", percent: 100, role: "ผู้เอาประกัน" }],
    beneficiaries: ["mother"],
    plan: "keep",
    documents: "complete",
    ownerEntityKind: "individual",
    recipientRelation: "spouse",
    otherDetails: { subtype: "other" },
  },
  {
    id: "a5",
    type: "finance",
    name: "กองทุนรวมตราสารหนี้",
    value: 12_400_000,
    valuationDate: "2569-02",
    ownership: [{ personId: "mother", percent: 100 }],
    beneficiaries: ["mother"],
    plan: "keep",
    documents: "complete",
    ownerEntityKind: "individual",
    otherDetails: { subtype: "fund" },
  },
  {
    id: "a6",
    type: "real_estate",
    name: "คอนโดสุขุมวิท",
    value: 18_500_000,
    valuationDate: "2568-11",
    ownership: [{ personId: "father", percent: 100 }],
    beneficiaries: ["eldest"],
    plan: "undecided",
    documents: "complete",
    ownerEntityKind: "individual",
    heirCount: 1,
    recipientRelation: "lineal_descendant",
    realEstate: {
      subtype: "condo",
      area: { rai: 0, ngan: 0, sqWah: 46.25 },
      appraisalPerSqWah: 400_000,
      salePrice: 19_000_000,
      acquiredYearBe: 2560,
      transferYearBe: 2569,
      acquisitionMethod: "purchase_or_other",
    },
  },
  {
    id: "a7",
    type: "business",
    name: "หุ้นบริษัท DEF (นอกตลาด)",
    value: 85_000_000,
    valuationDate: "2568-09",
    ownership: [
      { personId: "father", percent: 70 },
      { personId: "mother", percent: 30 },
    ],
    beneficiaries: ["eldest", "youngest"],
    plan: "undecided",
    documents: "incomplete",
    controlPersonId: "father",
    ownerEntityKind: "individual",
    heirCount: 2,
    recipientRelation: "lineal_descendant",
    share: {
      subtype: "unlisted",
      companyName: "บริษัท DEF จำกัด",
      registeredCapital: 50_000_000,
      ownershipPercent: 70,
      parValue: 35_000_000,
      bookValue: 85_000_000,
      costBasis: 25_000_000,
    },
  },
  {
    id: "a8",
    type: "finance",
    name: "เงินฝากประจำธนาคาร K",
    value: 22_000_000,
    valuationDate: "2569-01",
    ownership: [{ personId: "father", percent: 100 }],
    beneficiaries: ["mother", "eldest"],
    plan: "transfer",
    documents: "complete",
    ownerEntityKind: "individual",
    heirCount: 2,
    recipientRelation: "lineal_descendant",
  },
];

/** Ownership graphs per major asset — switchable on canvas */
export const INITIAL_OWNERSHIP_GRAPHS: OwnershipGraph[] = [
  {
    assetId: "a3",
    title: "หุ้น ABC",
    nodes: [
      {
        id: "a3-father",
        label: "คุณพ่อ",
        sublabel: "ถือ 60% · ควบคุม (ประธาน)",
        kind: "person",
        x: 280,
        y: 24,
      },
      {
        id: "a3-asset",
        label: "หุ้นบริษัท ABC จำกัด",
        sublabel: "มูลค่า ฿210M",
        kind: "asset",
        x: 250,
        y: 150,
      },
      {
        id: "a3-eldest",
        label: "บุตรคนโต",
        sublabel: "รับผลประโยชน์ 40%",
        kind: "person",
        x: 60,
        y: 300,
      },
      {
        id: "a3-youngest",
        label: "บุตรคนเล็ก",
        sublabel: "แผนอนาคต (รอตัดสินใจ)",
        kind: "person",
        x: 430,
        y: 300,
      },
    ],
    edges: [
      {
        id: "a3-e1",
        from: "a3-father",
        to: "a3-asset",
        label: "ถือครอง 60%",
      },
      {
        id: "a3-e2",
        from: "a3-asset",
        to: "a3-eldest",
        label: "ผลประโยชน์ 40%",
      },
      {
        id: "a3-e3",
        from: "a3-asset",
        to: "a3-youngest",
        label: "แผนอนาคต",
      },
    ],
  },
  {
    assetId: "a2",
    title: "ที่ดินบางละมุง",
    nodes: [
      {
        id: "a2-father",
        label: "คุณพ่อ",
        sublabel: "ถือ 50%",
        kind: "person",
        x: 120,
        y: 40,
      },
      {
        id: "a2-mother",
        label: "คุณแม่",
        sublabel: "ถือ 50%",
        kind: "person",
        x: 420,
        y: 40,
      },
      {
        id: "a2-asset",
        label: "ที่ดินบางละมุง",
        sublabel: "มูลค่า ฿38M",
        kind: "asset",
        x: 250,
        y: 170,
      },
      {
        id: "a2-eldest",
        label: "บุตรคนโต",
        sublabel: "ผู้รับโอนแผน",
        kind: "person",
        x: 40,
        y: 320,
      },
      {
        id: "a2-youngest",
        label: "บุตรคนเล็ก",
        sublabel: "ผู้รับโอนแผน",
        kind: "person",
        x: 250,
        y: 320,
      },
      {
        id: "a2-child3",
        label: "บุตรคนที่ 3",
        sublabel: "ผู้รับโอนแผน",
        kind: "person",
        x: 460,
        y: 320,
      },
    ],
    edges: [
      { id: "a2-e1", from: "a2-father", to: "a2-asset", label: "ถือ 50%" },
      { id: "a2-e2", from: "a2-mother", to: "a2-asset", label: "ถือ 50%" },
      { id: "a2-e3", from: "a2-asset", to: "a2-eldest", label: "แผนโอน" },
      { id: "a2-e4", from: "a2-asset", to: "a2-youngest", label: "แผนโอน" },
      { id: "a2-e5", from: "a2-asset", to: "a2-child3", label: "แผนโอน" },
    ],
  },
  {
    assetId: "a7",
    title: "หุ้น DEF",
    nodes: [
      {
        id: "a7-father",
        label: "คุณพ่อ",
        sublabel: "ถือ 70% · ควบคุม",
        kind: "person",
        x: 140,
        y: 40,
      },
      {
        id: "a7-mother",
        label: "คุณแม่",
        sublabel: "ถือ 30%",
        kind: "person",
        x: 400,
        y: 40,
      },
      {
        id: "a7-asset",
        label: "หุ้นบริษัท DEF",
        sublabel: "มูลค่า ฿85M",
        kind: "asset",
        x: 250,
        y: 170,
      },
      {
        id: "a7-eldest",
        label: "บุตรคนโต",
        sublabel: "ผู้รับผลประโยชน์",
        kind: "person",
        x: 100,
        y: 320,
      },
      {
        id: "a7-youngest",
        label: "บุตรคนเล็ก",
        sublabel: "ผู้รับผลประโยชน์",
        kind: "person",
        x: 400,
        y: 320,
      },
    ],
    edges: [
      { id: "a7-e1", from: "a7-father", to: "a7-asset", label: "ถือ 70%" },
      { id: "a7-e2", from: "a7-mother", to: "a7-asset", label: "ถือ 30%" },
      {
        id: "a7-e3",
        from: "a7-asset",
        to: "a7-eldest",
        label: "ผลประโยชน์",
      },
      {
        id: "a7-e4",
        from: "a7-asset",
        to: "a7-youngest",
        label: "ผลประโยชน์",
      },
    ],
  },
];

/** @deprecated kept for any residual imports */
export const INITIAL_DIAGRAM_NODES = INITIAL_OWNERSHIP_GRAPHS[0].nodes;
export const DIAGRAM_EDGES = INITIAL_OWNERSHIP_GRAPHS[0].edges;

export const INITIAL_TRANSFER_STEPS: TransferStep[] = [
  {
    id: "t1",
    yearLabel: "2569",
    title: "โอนหุ้น ABC 10% ให้บุตรคนเล็ก",
    note: "ใช้สิทธิยกเว้นภาษีการให้รายปี",
    estimatedTax: 0,
    status: "review",
    order: 0,
    assetId: "a3",
    registrationType: "gift",
    recipientRelation: "lineal_descendant",
    transferAmount: 21_000_000,
    heirCount: 1,
  },
  {
    id: "t2",
    yearLabel: "2570",
    title: "จัดทำพินัยกรรมฉบับใหม่",
    note: "ต้องมีพยาน 2 คน และเอกสารพินัยกรรม",
    estimatedTax: null,
    status: "not_started",
    order: 1,
  },
  {
    id: "t3",
    yearLabel: "2571",
    title: "โอนที่ดินบางละมุงรอบที่ 1",
    note: "โอนส่วนบุตรคนโต — ใช้สิทธิยกเว้นรายปี",
    estimatedTax: 0,
    status: "not_started",
    order: 2,
    assetId: "a2",
    registrationType: "gift",
    recipientRelation: "lineal_descendant",
    transferAmount: 12_666_667,
    heirCount: 1,
  },
  {
    id: "t4",
    yearLabel: "2572",
    title: "โอนที่ดินบางละมุงรอบที่ 2",
    note: "โอนส่วนบุตรคนกลาง",
    estimatedTax: 180_000,
    status: "not_started",
    order: 3,
    assetId: "a2",
    registrationType: "gift",
    recipientRelation: "lineal_descendant",
    transferAmount: 12_666_667,
    heirCount: 1,
  },
  {
    id: "t5",
    yearLabel: "2573",
    title: "โอนที่ดินบางละมุงรอบที่ 3",
    note: "โอนส่วนบุตรคนเล็ก — จบแผนที่ดิน",
    estimatedTax: 320_000,
    status: "not_started",
    order: 4,
    assetId: "a2",
    registrationType: "gift",
    recipientRelation: "lineal_descendant",
    transferAmount: 12_666_666,
    heirCount: 1,
  },
  {
    id: "t6",
    yearLabel: "2574",
    title: "ทบทวนกรรมสิทธิ์บัญชีลงทุน",
    note: "ปรับสัดส่วนผู้รับผลประโยชน์ตามพินัยกรรม",
    estimatedTax: null,
    status: "concept",
    order: 5,
  },
  {
    id: "t7",
    yearLabel: "2575",
    title: "โอนหุ้น ABC เพิ่มอีก 5%",
    note: "หลังประเมินมูลค่ากิจการรอบใหม่",
    estimatedTax: 450_000,
    status: "concept",
    order: 6,
    assetId: "a3",
    registrationType: "gift",
    recipientRelation: "lineal_descendant",
    transferAmount: 10_500_000,
    heirCount: 1,
  },
  {
    id: "t8",
    yearLabel: "ระยะยาว",
    title: "ทบทวนโครงสร้างหุ้น ABC",
    note: "พิจารณาจัดตั้ง holding company — ปรึกษาที่ปรึกษากฎหมาย",
    estimatedTax: null,
    status: "concept",
    order: 7,
  },
];

/** ค่าคงที่สำรอง — UI ใช้ summarizePortfolioTax จากทรัพย์สินจริง */
export const TAX_SUMMARY = {
  giftAccumulated: 0,
  inheritanceWithoutPlan: 6_300_000,
  remainingExemptionThisYear: 20_000_000,
};

export const DOCUMENT_ITEMS: DocumentItem[] = [
  {
    id: "d1",
    name: "หนังสือให้ (หุ้น ABC)",
    status: "draft",
    category: "gift",
    description: "ร่างหนังสือให้หุ้น 10% ตามขั้นโอนปี 2569 — รอตรวจทานโดยที่ปรึกษา",
    updatedLabel: "1 มี.ค. 2569",
    relatedStepId: "t1",
    relatedAssetId: "a3",
  },
  {
    id: "d2",
    name: "พินัยกรรมฉบับใหม่",
    status: "not_started",
    category: "will",
    description:
      "จัดทำพินัยกรรมระบุผู้รับมรดกและสัดส่วนทรัพย์สิน — ต้องมีพยานอย่างน้อย 2 คน",
    relatedStepId: "t2",
  },
  {
    id: "d3",
    name: "หนังสือมอบอำนาจ",
    status: "approved",
    category: "power_of_attorney",
    description: "มอบอำนาจให้บุตรคนโตดำเนินการโอนและติดต่อหน่วยงานที่เกี่ยวข้อง",
    updatedLabel: "15 ม.ค. 2569",
  },
  {
    id: "d4",
    name: "สำเนาโฉนดที่ดินบางละมุง",
    status: "draft",
    category: "ownership",
    description: "รวบรวมสำเนาโฉนดและเอกสารสิทธิ์ก่อนโอนรอบที่ 1",
    updatedLabel: "28 ก.พ. 2569",
    relatedAssetId: "a2",
    relatedStepId: "t3",
  },
  {
    id: "d5",
    name: "บัญชีทรัพย์สินแนบท้ายพินัยกรรม",
    status: "not_started",
    category: "will",
    description: "รายการทรัพย์สินและผู้รับผลประโยชน์ให้สอดคล้องกับแผนโอน",
    relatedStepId: "t2",
  },
  {
    id: "d6",
    name: "หนังสือรับรองบริษัท ABC",
    status: "approved",
    category: "ownership",
    description: "หนังสือรับรองการจดทะเบียนและรายชื่อผู้ถือหุ้นล่าสุด",
    updatedLabel: "10 ธ.ค. 2568",
    relatedAssetId: "a3",
  },
];
